name: CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOG }}
      NAME: ${{ secrets.DOCKER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Login to docker.io
        run: echo $PASSWORD | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t ${LOGIN/$NAME}:version1 -f Dockerfile .
